# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-24 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mailing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0438\u0441\u043e\u043a',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[mailing.validators.mail_text_validator], verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('date_mail', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='MailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': '\u0424\u0430\u0439\u043b \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
                'verbose_name_plural': '\u0424\u0430\u0439\u043b\u044b \u0440\u0430\u0441\u0441\u044b\u043b\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0447\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u041f\u043e\u0447\u0442\u044b \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('birthday', models.CharField(blank=True, max_length=255, verbose_name='\u0414\u0435\u043d\u044c \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u0435')),
                ('age', models.IntegerField(blank=True, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='mailing.List', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a',
                'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='mail',
            name='files',
            field=models.ManyToManyField(related_name='mails', to='mailing.MailFile', verbose_name='\u0424\u0430\u0439\u043b\u044b'),
        ),
        migrations.AddField(
            model_name='mail',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mailing.List', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mailing.SenderEmail', verbose_name='Email \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
