# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-24 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442'),
        ),
    ]
