# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20221124_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sender_email',
            field=models.CharField(max_length=255, verbose_name='\u041f\u043e\u0447\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
