# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20221125_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderemail',
            name='owner',
        ),
        migrations.DeleteModel(
            name='SenderEmail',
        ),
    ]
