# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20221125_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='files',
        ),
        migrations.AddField(
            model_name='mail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b'),
        ),
        migrations.DeleteModel(
            name='MailFile',
        ),
    ]
