# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20221125_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
    ]
