# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_mail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='send',
            field=models.BooleanField(default=True, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c'),
        ),
    ]
